### PR TITLE
no more setState on unmounted component

### PR DESCRIPTION
**Pull request by Emad-Emami**
error: `react-dom.development.js?61bb:506 Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.`
[Dan Abramov suggestion](https://github.com/facebook/react/issues/14369#issuecomment-468267798)

### CODE REVIEW

**Comment by bence-toth** [comment]
Nice catch, thank you for the contribution @Emad-Emami! :heart: 

I'll make sure and publish a new version of the npm package with this fix soon.

**Comment by bence-toth** [comment]
@Emad-Emami this was just published to npm with 1.0.5. Thank you again!

**Comment by Emad-Emami** [comment]
@bence-toth You are welcome, but there is no `dist` folder!
didn't you build and then publish?

**Comment by bence-toth** [comment]
Yes, it was my bad, I totally did publish without building. 1.0.6 it is, it just hit the registry. I also tested it _after_ publishing this time.

**Pull request merged**
